### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by yangxu1231** [Jaskiee/GAN-Attack-against-Federated-Deep-Learning#2]
So lucky to see your code! I'm a graduate from NUDT and I have some trouble in understanding some part of it, so i want to ask some details from you, would you like to leave a mail or something.

**Comment by Jaskiee** [comment]
Sure, my email is `[xiesiqi@whu.edu.cn](url)`.

**Comment by Jaskiee** [comment]
Sure, my email is xiesiqi@whu.edu.cn
